### ISSUE TITLE
Recursive upgradeable lock acquisitions not allowed in this mode

### ISSUE THREAD

**Issue by JustinDWright** [MindfireTechnology/BlazorStateManager#4]
When calling `await Events.Publish<bool>(this, KeyConstants.CheckoutFlowSuccessTopic, true);` after previous successful calls, I'm getting Recursive upgradeable lock acquisitions not allowed in this mode.

See issue in https://stackoverflow.com/c/mindfire-technology/questions/79

**Comment by nzaugg** [comment]
I'm looking into this

**Comment by nzaugg** [comment]
This has been fixed for some time now
